config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 root to: "home#guestfeed"
 get 'newest', to: 'home#newest'
 get 'feed', to: 'home#feed'
 get 'discover', to: 'home#discover'
 resources :users ,except: [:index, :destroy] do
   member do
     get 'profile', to: 'home#profile'
  end
  resource :photos
  resource :albums
 end
 resources :photos ,except: ['show']
 resources :albums ,except: ['show']
 namespace :admin do
   resources :users, shallow: true
 end
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many:photos
  has_many :likes, as: :likeable
  validates :title, presence: true, length: {maximum: 140,minimum:10, message:"max",message:"SERVER: AT LEAST 10 CHARACTERS"}
  validates :description,length: {maximum: 300}
  before_save :ensure_description_has_value
  private
    def ensure_description_has_value
      unless self.description.present?
        self.description= "This is album of user has id " + self.user_id.to_s
      end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: :follower_id, class_name: "User"
  belongs_to :followed_user, foreign_key: :followed_user_id, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
  belongs_to :user
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many:albums
  has_many :likes, as: :likeable
  validates :title, presence: true, length: {maximum: 140}
  validates :description, presence: true, length: {maximum: 300}
  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable


  has_many :albums
  has_many :photos
  has_many :likes
  validates :first_name, presence: true, length: {maximum: 25, message: "Your first name is too loooong"}, format: { with: /\A[a-zA-Z]+\z/}, uniqueness: {scope: :last_name}
  validates :last_name, presence: true, length: {maximum: 25, message: "Your last name is too loooong"}, format: { with: /\A[a-zA-Z]+\z/}
  validates :email, presence: true, length: {maximum: 255, message:"Your email is too loooong"}, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,message:"that not a email"},uniqueness:true
  validates :password, presence:true, confirmation: true, length: {minimum: 8,maximum: 64, message: "Your password must has at least 8 and at most 64 characters!"}
  has_many :received_follows, foreign_key: :followed_user_id, class_name: "Follow"
  has_many :followers, through: :received_follows, source: :follower
  has_many :given_follows, foreign_key: :follower_id, class_name: "Follow"
  has_many :followings, through: :given_follows, source: :followed_user
  after_save :sendmail
  private
    def sendmail
      SendEmailJob.perform_later self
    end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def edit
    @c=0
    @album=Album.find(params[:id])
    render 'edit_album_title'
  end
  def update
    @album=Album.find(params[:id])
    @c=1
    @title=params.require(:album).permit(:title)
    @album.update(title: @title["title"])
    render 'edit_album_title'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?
    protected

    def configure_permitted_parameters
      added_attrs = [:first_name,:last_name, :email, :password, :password_confirmation, :remember_me]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    end
 end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, :except => [:guestfeed]
  def guestfeed
    render 'guestfeed'
  end

  def newest
    @a= Album.order(created_at: :desc).limit(4)
    @c=0
    render 'newest'
  end
  def feed
    @u=User.find_by(id:17)
    @p=Photo.order(created_at: :desc).limit(6)
    @a=Album.order(created_at: :desc).limit(6)
    render 'feed'
  end
  def discover
    @u=User.find_by(id:17)
    @p=Photo.order(created_at: :desc).limit(6)
    @a=Album.order(created_at: :desc).limit(6)
    # @l=User.find_by(id:1)
    render 'discover'
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def index
   @photo = Photo.order('created_at DESC')
  end
  def new
    @photo=Photo.new
    @user = User.find_by(id: user_info)
  end

  def create
    @photo = Photo.new photo_params
    @photo.user_id = user_info
    if @photo.save
      flash[:success] = "New photo has been successfully added."
      redirect_to action: :new
    else
      flash[:error] = @photo.errors.full_messages[0]
      redirect_to action: :new
    end
  end

  def edit
    @photo=Photo.find(params[:id])
    render :edit
  end

  def update

    @photo = Photo.find(params[:id])
    if @photo.update_attributes(photo_params)
      redirect_to
    else
      render :edit
    end
  end
  private
  def user_info
      params.require(:user_id)
    end
  def photo_params
    params.require(:photo).permit(:title, :description, :image,:public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    render root_path
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new user_detail

    if @user.save
      UserMailer.sample_email(@user).deliver_now
      flash[:success] = "User was successfully created."
      redirect_to action: :new
    else
      flash[:error] = @user.errors.full_messages[0]
      redirect_to action: :new
    end
  end

  private
    def user_detail
      params.require(:user).permit(:last_name, :first_name, :password, :email)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/edit_album_title.html.erb
<%= form_for @album,:html =>{:id => "Edit_form"} do |f| %>
  Old title : <%=  @album.title%><br>
  <%= f.text_field :title%>
  <%= submit_tag "Submit" %>
<% end %>

<% if  @album.errors.any? %>
  <% flash.now[:alert]=@album.errors.full_messages.first %>
<% elsif @c != 0 %>
  <% flash.now[:success]="update success" %>
<% end %>


<%= render_flash_messages %>

<script type="text/javascript">
$(document).ready(function(){
  $('#Edit_form').validate({
      rules:{
        "album[title]": "required"
      },
      messages:{
        "album[title]": "Please enter title!"
      }
    })
})
</script>
<script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.2/dist/jquery.validate.min.js"></script>

app/views/home/discover.html.erb
<%= stylesheet_link_tag "fotobook_style" %>
<%= javascript_pack_tag 'script'%>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>



<div class="container-fluid">
  <div class="navbar row py-1" style="background-color: #3C5999;" >
          <div class="col-2 col-sm-3 col-md-2 text-right">
              <a class="text-white ml-1" style="font-size:20px" href="">Fotobook</a>
          </div>
          <div class="col-6 col-sm-6 col-md-6">
              <input class="rounded border-light w-75" name="search_bar" id="search_bar" type="text" placeholder="Search Photo / Album"></input>
          </div>
          <div class="col-4 row col-sm-3 col-md-4 pl-5 text-right pr-5"style="height:40px" >
            <div class="col-md-7 col-12">
              <a class="btn rounded-circle bg-white text-color border-0 px-2" href="my_profile.html"><%=@u.last_name[0]%><%=@u.first_name[0]%></a>
              <a class="btn border-0 text-white hidden-xs" href="my_profile.html"><%=@u.first_name%> </a>
            </div>
            <div class=" col-md-5 text-center hidden-xs justify-content-center">
              <%= link_to "Logout", destroy_user_session_path, {class: "nav-item nav-link btn border-0 text-white", method: "delete"}%>
            </div>
          </div>

      </div>
    <div class="row p-3 justify-content-center grey_background">
      <div class="col-2 pt-4 align-items-center">
        <div class="row col ml-2">
          <a class="btn text-secondary head_font" href="feed.html">Feeds</a>
        </div>
        <div class="row col ml-2">
          <a class="btn head_font fb_color" href="#" ><b>Discover</b></a>
        </div>
      </div>


      <div class="col-12 col-sm-9 row d-flex justify-content-center bg-white text-dark">
        <div class="col-12 d-flex justify-content-center">
        <div class="m-3 btn-group">
          <button class="btn rounded-left border chosen fb_background" id="btn-photo">PHOTO</button>
          <button class="btn rounded-right border" id="btn-album">ALBUM</button>
        </div> <br>
      </div>



      <div id="photo_tab" class="">
        <div class=" row d-flex justify-content-center px-0">
        <% @p.each do |i| %>
          <!-- model begin -->
          <div class="col-12 col-md-5 m-2 row grey_background rounded shadow">
              <div class="col-12 col-md-6 d-flex justify-content-center">
                <div class="d-flex justify-content-center discover_album">
                  <img src="photo/batman.jpg" alt="batman" class="img-fluid img-thumbnail position-absolute discover_album"/>
                </div>
              </div>
              <div class="col-12 col-md-6">
                <div class="row justify-content-between align-items-center" name="info-part">
                  <div class="col-8">
                    <div class="row mb-2">
                      <button class="rounded-circle chosen border-0"><%= i.user.last_name[0].upcase %><%= i.user.first_name[0].upcase %></button>
                      <a href="#" class="btn font-size"><%= i.user.first_name %></a>
                    </div>
                  </div>
                  <div class="col-4 pr-2">
                    <button class="btn btn-sm font-size-sm followed rounded-pill px-1 py-0" name="follow">Following</button>
                  </div>

                </div>
                <div class="row font-weight-bold" name="title-post">
                  <%= i.title %>
                </div>
                <div class="row overflow-auto" name="description-post">
                  <%= i.description %>
                </div>
                <div class="row justify-content-between align-items-center top-100 feed_footer">
                  <div class="col-auto text-color font-size love">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16" fill="rgb(60, 90, 154)"><path fill-rule="evenodd" d="M7.655 14.916L8 14.25l.345.666a.752.752 0 01-.69 0zm0 0L8 14.25l.345.666.002-.001.006-.003.018-.01a7.643 7.643 0 00.31-.17 22.08 22.08 0 003.433-2.414C13.956 10.731 16 8.35 16 5.5 16 2.836 13.914 1 11.75 1 10.203 1 8.847 1.802 8 3.02 7.153 1.802 5.797 1 4.25 1 2.086 1 0 2.836 0 5.5c0 2.85 2.045 5.231 3.885 6.818a22.075 22.075 0 003.744 2.584l.018.01.006.003h.002z"></path></svg><span>123</span>
                  </div>
                  <div class="col-auto text-secondary font-size-sm">
                  <%=i.created_at.to_s(:time)%> <%=i.created_at.to_date%>
                  </div>
                </div>
              </div>
            </div>
            <!--model end-->
            <!-- model begin -->
              <!--model end-->
        <%end%>
        </div>
      </div>




      <div id="album_tab" class="d-none">
        <div class="row d-flex justify-content-center px-0">
        <% @a.each do |i| %>
          <!-- model begin -->
          <div class="col-12 row col-md-5 grey_background rounded shadow m-3">
              <div class="col-12 col-md-6 d-flex justify-content-center pr-5">
                <div class="d-flex mt-3 justify-content-center discover_album">
                  <img src="photo/batman.jpg" alt="batman" class="img-fluid img-thumbnail position-absolute rotate_pic2 discover_album"/>
                  <img src="photo/batman.jpg" alt="batman" class="img-fluid img-thumbnail position-absolute rotate_pic1 discover_album"/>
                  <img src="photo/batman.jpg" alt="batman" class="img-fluid img-thumbnail position-absolute discover_album"/>
                </div>
              </div>
              <div class="col-12 col-md-5">
                <div class="row justify-content-between align-items-center" name="info-part">
                  <div class="col-8">
                    <div class="row mb-2">
                      <button class="rounded-circle chosen border-0"><%= i.user.last_name[0].upcase %><%= i.user.first_name[0].upcase %></button>
                      <a href="#" class="btn font-size"><%=i.user.first_name%></a>
                    </div>
                  </div>
                  <div class="col-4 pr-2">
                    <button class="btn btn-sm font-size-sm followed rounded-pill px-1 py-0" name="follow">Following</button>
                  </div>

                </div>
                <div class="row font-weight-bold" name="title-post">
                   <%=i.title %>
                </div>
                <div class="row" name="description-post">
                  <%=i.description %>
                </div>
                <div class="row justify-content-between align-items-center top-100 feed_footer">
                  <div class="col-auto text-color font-size love">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16" fill="rgb(60, 90, 154)"><path fill-rule="evenodd" d="M7.655 14.916L8 14.25l.345.666a.752.752 0 01-.69 0zm0 0L8 14.25l.345.666.002-.001.006-.003.018-.01a7.643 7.643 0 00.31-.17 22.08 22.08 0 003.433-2.414C13.956 10.731 16 8.35 16 5.5 16 2.836 13.914 1 11.75 1 10.203 1 8.847 1.802 8 3.02 7.153 1.802 5.797 1 4.25 1 2.086 1 0 2.836 0 5.5c0 2.85 2.045 5.231 3.885 6.818a22.075 22.075 0 003.744 2.584l.018.01.006.003h.002z"></path></svg><span>123</span>
                  </div>
                  <div class="col-auto text-secondary font-size-sm">
                    <%=i.created_at.to_s(:time)%> <%=i.created_at.to_date%>
                  </div>
                </div>
              </div>
            </div>
            <!--model end-->
            <!-- model begin -->
              <!--model end-->
        <% end%>
        </div>
      </div>




        <!-- End -->
        <div class="row bg-white mt-5 justify-content-center " style="height:50px">
          <div class="spinner-border text-secondary" role="status">
            <span class="sr-only">Loading...</span>
          </div>
        </div>
      </div>
      <div class="col">
      </div>
    </div>



  </div>

  <div id="modal-photo" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header border-0">
          <p class="modal-title font-weight-bold" id="modal-photo-title"></p>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body my-n1 py-0">
          <img src="" class="img" id="modal-photo-body" style="width:100%"/>
          <p id="modal-photo-description" style="font-size:10px" class="pt-2"></p>
        </div>
      </div>
    </div>
  </div>

  <div id="modal-album" class="modal" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header border-0">
            <p class="modal-title font-weight-bold" id="modal-album-title"></p>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body my-n1 py-0">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="photo/batman.jpg" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                  <img src="photo/batman.jpg" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                  <img src="photo/batman.jpg" class="d-block w-100" alt="...">
                </div>
              </div>
              <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
            <p id="modal-album-description" style="font-size:10px" class="pt-2"></p>
          </div>
        </div>
      </div>
    </div>

app/views/home/newest.html.erb
<h1>Lastest Album</h1>
<div class="row" style="border:1px grey solid;">
<% @a.each do |album| %>
  <div class="col-lg-3 col-md-6 col-sm-12"  style="border:1px grey solid;">
    <% @c=@c+1%>
    Album  <%= @c%> : <%= album.title %>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'script', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>


  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice%></p>
    <p class="alert"><%= alert%></p>
  </body>
</html>

app/views/photos/edit.html.erb
<%= form_for @photo do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <%= f.submit %>
<% end %>

app/views/photos/new.html.erb
<%= stylesheet_link_tag "fotobook_style" %>
<%= javascript_pack_tag 'script'%>
  <div class="container-fluid">
    <div class="navbar row py-0" style="background-color: #3C5999 ">
            <div class="col-2 text-right">
                <a class="text-white ml-2" style="font-size:20px" href="feed.html">Fotobook</a>
            </div>
            <div class="col-7">
                <input class="rounded border-light" name="search_bar" style="width:600px; height:32px" id="search_bar" type="text" placeholder="Search Photo / Album"></input>
            </div>
            <div class="col-3 row justify-content-between" >
              <div class="col-6">
                <a class="btn rounded-circle bg-white text-color border-0 px-2" href="my_profile.html">DB</a>
                <a class="btn text-white border-0" href="my_profile.html">Duc Bo</a>
              </div>
              <div class="col-6">
                <a class="text-white pl-5" style="font-size:20px" href="">Login</a>
              </div>
            </div>
      </div>
      <div class="row p-3 justify-content-center" style="background-color:#F8F8F8">
        <div class="col-2 pt-4 align-items-center">
          <div class="row col ml-2">
            <a class="btn text-secondary" href="feed.html" style="font-size:20px" >Feeds</a>
          </div>
          <div class="row col ml-2">
            <a class="btn text-secondary" href="#" style="font-size:20px" >Discover</a>
          </div>
        </div>
      <div class="col-9 p-3">
        <div class="col bg-white pb-3 mb-5">

          <div class="font-weight-bold border-bottom py-4" style="font-size:20px;">New Photo</div>
          <%= form_for @photo, url: new_user_photos_path(user_id: params.require(:user_id)), method: :post do |f| %>
          <div class="row">
            <div class="col px-4">
              <div class="form-group-vertical mt-4">
                <%= f.label :title %>
                <%= f.text_field :title, placeholder: "Photo Title", class:"form-control col-11" %>
              </div>
              <div class="form-group-vertical my-4">
                  <%= f.label :public, "Sharing mode" %> <br/>
                  <%= f.select(:public, ['Public', 'Private'], {}, { :class => 'col-lg-5 col-md-11 custom-select' }) %>
              </div>
            </div>
            <div class="col px-4">
              <div class="form-group-vertical mt-4">
                <%= f.label :description %>
                <%= f.text_field :description, placeholder: "Photo Description", class:"form-control" %>
              </div>
            </div>
          </div>
          <div class="row mx-2 my-3">
            <div class="row form-group-vertical border-dash border rounded justify-content-center pt-5" style="height:200px; width:200px;background-image: url('photo/add3.png');background-size:cover">
              <!-- <label for="new_album"></label>
              <input type="file" name="new_album" class="" accept="image/*" style="opacity:0;height:200px;width:200px"/> -->
              <%= f.label :image %>
              <%= f.file_field :image %>
            </div>
          </div>
          <div class="row mx-2 my-5">
              <%= f.submit "Save"%>
          </div>
          <% end %>
        </div>
      </div>
      <div class="col">
      </div>
    </div>
  </div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="js/script.js"></script>

app/views/users/_form.html.erb
<%= form_for @user, html: { multipart: true } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="post__inarticle-ad-template" style="margin-top: 30px;"><div class="avert fuse-ad"><div class="avert__wrapper"><div class="avert__content"><div data-fuse="21764347426"></div></div><div class="avert__label">Advertisement</div></div></div></div><div class="post__inarticle-ad-1-template-mobile" style="display: block; margin-top: 30px;"><div class="avert fuse-ad"><div class="avert__wrapper"><div class="avert__content"><div data-fuse="21764355534"></div></div><div class="avert__label">Advertisement</div></div></div></div><h2 class="nolinks"><%= pluralize(@user.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!--  <style>div{border:solid red;}</style>-->
    <title>Sign up</title>
  </head>
  <body>

    <%= form_for @user do |f| %>
       <%= f.text_field :first_name, placeholder: "Firstname" %>
       <%= f.text_field :last_name, placeholder: "Lastname"%>
       <%= f.password_field :password, placeholder: "Paswword"%>
       <%= f.email_field :email, placeholder: "Email"%>
       <%= submit_tag "Create" %>
    <% end %>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= "#{value}" %></div>
    <% end %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>